version: "3"
services:
  app:
    image: sensortag
    container_name: sensortag
    network_mode: "host"
    volumes:
      - ./conf:/home/app/conf
      - ./src/index.js:/home/app/index.js
      - ./src/st.js:/home/app/st.js
      - ./src/package.json:/home/app/package.json
    build:
      context: .
